server:
  port: 8082

spring:
  application:
    name: zhangliao_mybatis_plus_Transcational

  profiles:
    active: local
    #active: h2

  datasource:
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      max-lifetime: 28000000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      connection-test-query: SELECT 1
      validation-timeout: 3000

mybatis-plus:
  configuration:
    cache-enabled: false
    local-cache-scope: statement
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false


